environment: production
chdir: /home/qiuchu
address: 127.0.0.1
user: root
group: root
port: 5000
pid: /home/qiuchu/thin.pid
rackup: /home/qiuchu/config.ru
log: /home/qiuchu/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true

